apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-books
  labels:
    app: api-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-books
  template:
    metadata:
      labels:
        app: api-books
    spec:
      containers:
      - name: api-books
        image: apolzek/api-books:v1.7
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: api-books
spec:
  selector:
    app: api-books
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000