apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-example
spec:
  serviceName: mongo-example
  replicas: 1
  selector:
    matchLabels:
      app: mongo-example
  template:
    metadata:
      labels:
        app: mongo-example
        selector: mongo-example
    spec:
      containers:
      - name: mongo-example
        image: mongo:7.0
        ports:
        - containerPort: 27017
          name: mongo
        livenessProbe:
          tcpSocket:
            port: mongo
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: mongo
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      #   env:
      #     - name: MONGO_INITDB_ROOT_USERNAME
      #       valueFrom:
      #         secretKeyRef:
      #           name: mongo-credentials
      #           key: username
      #     - name: MONGO_INITDB_ROOT_PASSWORD
      #       valueFrom:
      #         secretKeyRef:
      #           name: mongo-credentials
      #           key: password
      # nodeSelector:
      #   kubernetes.io/hostname: mongodb-node

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-example
spec:
  selector:
    app: mongo-example
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
